### ISSUE TITLE
Additional CPU & GPU temperature SMC keys

### ISSUE THREAD

**Issue by beltex** [beltex/SMCKit#12]
- Minor
- No Mac with more than two GPUs, correct? 15"/17" MacBook Pro & Mac Pro
- As for CPU, do individual cores count? Unlikely each has a temperature sensor, maybe in the newer chips. If not, again, should be a max of two separate CPUs (Mac Pro)
    - Highest current is dual hexa-core (24 logical) Mac Pro
    - We can get the number of physical cores at runtime via Mach call, but this won't help as Temperature enum is fixed

**Comment by jBot-42** [comment]
I submitted a list in #22.

**Comment by beltex** [comment]
This was addressed in #23 with the new `SMCKit.allUnknownTemperatureSensors()`, which when paired with `SMCKit.allKnownTemperatureSensors()`, provides a complete list for the machine in question.
