### ISSUE TITLE
How to use in a swift project

### ISSUE THREAD

**Issue by dducro** [beltex/SMCKit#16]
Hey,

I imported SMC.swift in my project.
However I can't get it to print the current Temperature values.
The following prints an empty array and 0.0 for every Temperature sensor.
Am I missing something?

```
let smc = SMC()
println(smc.getAllValidTemperatureKeys())
for tempKey in enumerate(SMC.Temperature.allValues) {
    println(smc.getTemperature(tempKey.element.0, unit: SMC.TemperatureUnit.Celsius).0)
}
```

**Comment by beltex** [comment]
Hi @dducro!

You have to call the `open()` method first to get a connection to the SMC driver (and make sure to call `close()` when your done!)

Here's a simple example:

```swift
import IOKit

var smc = SMC()
if smc.open() != kIOReturnSuccess {
    println("ERROR: Failed to open connection to SMC")
} else {
    let temperatureSensors = smc.getAllValidTemperatureKeys()

    for key in temperatureSensors {
        let temperatureSensorName = SMC.Temperature.allValues[key]!
        let temperature           = smc.getTemperature(key).tmp

        println("\(temperatureSensorName): \(temperature)°C")
    }
    
    smc.close()
}
```

Take a look at the [SMCKitTool](https://github.com/beltex/SMCKit/blob/master/SMCKitTool/main.swift) source for more detail. Hope that helps!

**Comment by dducro** [comment]
Awesome! Thanks for the example!

Is it possible to run SMCKit alongside SystemKit?

**Comment by beltex** [comment]
np!

Absolutely, [dshb](https://github.com/beltex/dshb) does exactly that :)
