### ISSUE TITLE
Is it safe to run this command?

### ISSUE THREAD

**Issue by josejmoran** [beltex/SMCKit#25]
I did the installation on my iMac.  I can run smckit perfectly, but my HDD fan shows Current: 0 RPM.
That is my problem I changed my HD because the original one failed. I put a Western Digital and the sensor cable did not match. I got one for the Western Digital but it seems is not reporting temp data back.  The HD fan is running high.  Can I use this command to set the speed of the HD fan:
sudo smckit -n 1 -s 1102? Is it safe to run this?

**Comment by beltex** [comment]
Hello @josejmoran!

Sorry about the late response!

I'm surprised the HD fan would drop 0 RPM even though its not getting a reading from temperature sensor.

> Can I use this command to set the speed of the HD fan: sudo smckit -n 1 -s 1102?

Yes! That is the correct command assuming you want to set the second fan.

> Is it safe to run this?

There are no guarantees of course, especially when tinkering with hardware, but it should be a safe command to run. It simply sets the minimum fan speed. OS X itself will interject if it needs to raise it. In addition, it doesn't persist after reboot. Finally, you can always [reset your SMC](https://support.apple.com/en-ca/HT201295) incase of any issues.

You might also want to cross-check with the [Apple Hardware Test/Diagnostics](https://support.apple.com/en-ca/HT201257) incase there is some other issue here.
